# Generated by Django 4.0.3 on 2022-06-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbateros', '0005_alter_autor_options_alter_categoria_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.URLField(max_length=280),
        ),
    ]
